name = "gdoc-watcher"
main = "src/index.ts"
compatibility_date = "2023-12-22"

[triggers]
crons = [ "0 0 * * *" ]

[placement]
mode = "smart"

[observability]
enabled = true

[env.ifsclchangelog]

kv_namespaces = [
    { binding = "DOC_CACHE", id = "27760caf375f42f19174689a7fb7e1f3" }
]

[env.demo]

kv_namespaces = [
    { binding = "DOC_CACHE", id = "/change/to/your/KV/namespace/id/" }
]